const headers = [
  {
    value: "round",
    title: "Round",
    type: "ReadOnly",
    width: 65,
    numeric: true,
    padding: "dense",
  },
  {
    value: "style_code",
    title: "Style Code",
    type: "TextField",
    width: 90,
    numeric: true,
    padding: "none",
  },
  {
    value: "pieces",
    title: "PPC",
    type: "TextField",
    width: 50,
    numeric: true,
    padding: "none",
  },
  {
    value: "assembly_flow",
    title: "Assembly Flow",
    type: "TextField",
    width: 125,
    numeric: false,
    padding: "none",
  },
  {
    value: "program",
    title: "Program",
    type: "TextField",
    width: 125,
    numeric: false,
    padding: "none",
  },
  {
    value: "mold_skin_style",

    title: "MoldSkin/Style",
    type: "TextField",
    width: 225,
    numeric: false,
    padding: "default",
  },
  {
    value: "notes",
    title: "Notes",
    type: "TextField",
    width: 250,
    numeric: false,
    padding: "default",
  },
  {
    value: "rework_color_chart",
    title: "Rework Color Chart",
    type: "TextField",
    width: 200,
    numeric: false,
    padding: "none",
  },
  {
    value: "color",
    title: "Color",
    type: "TextField",
    width: 125,
    numeric: false,
    padding: "default",
  },
  {
    value: "add_take_off",
    title: "ATO",
    type: "TextField",
    width: 50,
    numeric: true,
    padding: "none",
  },
  {
    value: "total_crs",
    title: "Total Crs",
    type: "TextField",
    width: 75,
    numeric: true,
    padding: "none",
  },
  {
    value: "total_pcs",
    title: "Total PCS",
    type: "TextField",
    width: 90,
    numeric: true,
    padding: "none",
  },
  {
    value: "customer",
    title: "Customer",
    type: "TextField",
    width: 100,
    numeric: false,
    padding: "none",
  },
  {
    value: "crs_real_time",
    title: "CRS",
    type: "TextField",
    width: 150,
    numeric: true,
    padding: "none",
  },
  {
    value: "wip_density",
    title: "WIP Density",
    type: "TextField",
    width: 110,
    numeric: true,
    padding: "none",
  },
  {
    value: "loc",
    title: "WIP Location",
    type: "TextField",
    width: 200,
    numeric: false,
    padding: "none",
  },
  {
    value: "assy_build_option",
    title: "Build Option",
    type: "TextField",
    width: 150,
    numeric: false,
    padding: "none",
  },
];

export { headers };
